server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://47.94.235.246:3306/meiwen
    username: root
    password: qddpassword

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.xiaomy.book_city.mapper  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql