server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://47.94.235.246:3306/meiwen
    username: root
    password: qddpassword

## ??????????????????к???????????????÷???spring???????????????????????
mybatis:
  mapper-locations: classpath:mapper/*.xml  #??????????mapper???xml?????????·??
  type-aliases-package: com.xiaomy.book_city.mapper  # ????????????·??

  configuration:
    map-underscore-to-camel-case: true

#pagehelper：https://github.com/pagehelper/Mybatis-PageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      xiaomy:
        book_city:
          mapper: debug


